### ISSUE TITLE
trafficblocker blocklist KeyError

### ISSUE THREAD

**Issue by toffee** [HolgerHees/smartserver#10]
Not sure if it's a defect or wrong configuration in my side, anyway I will let you know.

I'm getting the following error:
```
[ERROR] - [m_service.lib.influxdb:66] - Traceback (most recent call last):
  File "/etc/system_service/lib/influxdb.py", line 62, in run
    messurements += callback()
                    ^^^^^^^^^^
  File "/etc/system_service/lib/trafficwatcher/trafficblocker/trafficblocker.py", line 264, in getMessurements
    messurements.append("trafficblocker,extern_ip={},blocking_state={},blocking_reason={},blocking_list={},blocking_count={} value=\"{}\"".format(ip, data["state"], data["reason"], data["blocklist"], data["count"], data["last"]))
                                                                                                                                                                                     ~~~~^^^^^^^^^^^^^
KeyError: 'blocklist'
```

If I delete the /dataDisk/var/lib/system_service/trafficblocker.json file (version 3) the error is gone, but the file is empty for the moment.  Previously, the file contains entries like (all missing blocklist):
```
"146.190.40.112": {
    "count": 1,
    "created": 1692759673.4107,
    "details": "scanning",
    "last": 1692759617.3242,
    "reason": "apache",
    "state": "blocked",
    "type": "unknown",
    "updated": 1692759673.4107
},
```

**Comment by HolgerHees** [comment]
Sorry for my late answer. Deleting the file was the correct solution. The json file is just a kind of cache and I changed the format without increasing the version.
